# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '12.0'

target 'FoodNFriends' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodNFriends
  pod 'GoogleMaps', '6.0.1'
  pod 'Alamofire'
  pod 'SwiftyJSON'
end
